---
train:

    params:
        batch_size: 32
        epoch: 12
        lr: 0.0005
        decay: 0.5
        decay_step: 10
        warmup: 3

    save:
        metapath: "/tudelft.net/staff-umbrella/StudentsCVlab/mverschure/results"
        folder: eth
        model_name: trans6
        step: 3

    data:
        image: "/tudelft.net/staff-umbrella/StudentsCVlab/mverschure/data/image/train"
        label: "/tudelft.net/staff-umbrella/StudentsCVlab/mverschure/data/label/train.label"
        header: True
        name: eth
        isFolder: False

    pretrain:
        enable: False
        path: PLACEHOLDER
        device: PLACEHOLDER

    device: 0

    reader: reader

# dropout = 0
# dim_feed = 512
